"""employees support console fields

Revision ID: da7e2e928e54
Revises: 0001
Create Date: 2026-01-02 03:42:43.296697

"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = 'da7e2e928e54'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('employees', sa.Column('role', sa.String(length=200), nullable=False))
    op.add_column('employees', sa.Column('pay_type', sa.String(length=20), nullable=False))
    op.add_column('employees', sa.Column('rate', sa.Numeric(scale=2), nullable=False))
    op.add_column('employees', sa.Column('default_hours', sa.Numeric(scale=2), nullable=False))
    op.add_column('employees', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('employees', sa.Column('tax', sa.String(length=20), nullable=False))
    op.alter_column('employees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('employees', 'hire_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('employees', 'annual_salary',
               existing_type=sa.NUMERIC(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'annual_salary',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('employees', 'hire_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('employees', 'tax')
    op.drop_column('employees', 'status')
    op.drop_column('employees', 'default_hours')
    op.drop_column('employees', 'rate')
    op.drop_column('employees', 'pay_type')
    op.drop_column('employees', 'role')
    op.drop_column('employees', 'name')
    # ### end Alembic commands ###
